services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons:rw
      - ./config:/etc/odoo:rw
      - ./odoo-web-data:/var/lib/odoo:rw
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - D:/ODOO19/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
